pipeline{
    agent any
    stages{
        stage('Launch'){
            steps{
              sh 'docker run --name calculator --network host -d calculator:1.0'
              
            }
        }
    }
}
